### ISSUE TITLE
Installation in the Azure Cloud Shell fails

### ISSUE THREAD

**Issue by alexandair** [Azure/simdem#19] opened 2017-08-13 21:33 UTC
```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python3.5/shutil.py", line 115, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/itsdangerous.py'
```

**Comment by SorraTheOrc** [comment] 2017-08-13 23:19
Can you please provide steps to reproduce this. I just installed on my cloudshell following the instructions in the readme and was unable to reproduce this error.

**Comment by alexandair** [comment] 2017-08-13 23:34
I've tried `git clone git@github.com:rgardler/simdem.git` and it failed with error:
Permission denied (publickey).

So, I've cloned with `git clone https://github.com/rgardler/simdem.git` and that worked.

After that I've executed:
```
cd simdem
./scripts/install.sh
```

And got two messages about missing sudo command at line 29 (expected, as we are regular users in Cloud Shell), a bunch of "Requirement already satisfied." messages, and then the previously mentioned exception.

**Comment by SorraTheOrc** [comment] 2017-08-14 01:52
The first error (public key)  means you don't have SSH keys setup for GitHub. I've changed the instructions to use https (and corrected to the Azure org now we have moved code over here).

The requirements already satisfied are not a concern.

Your report potentially highlights the problem though...

You shouldn't see the need for sudo command. Cloudshell is running in a Docker container so there is no sudo. I can see a recent change removed the check for this in the install script.

I'll submit a patch soon and notify this thread.

**Comment by SorraTheOrc** [comment] 2017-08-14 02:31
I think PR #20 should fix this, but since it worked for me before these changes it's possible I haven't fixed it yet. would appreciate you testing that PR for me.

**Comment by SorraTheOrc** [comment] 2017-08-16 15:55
PR #20 fixes the install. But SimDem fails to execute (see #22)

The problem is that we now create a virtual env for SimDem, but that prevents the Azure CLI working (as reported in #22). The VirtualEnv was introduced because of the need to install Flask, which Cloudshell wouldn't let us do without virtual env.

Two possible solutions to explore:
1) Make the WebUI a plugin and don't use it in CloudShell
2) Install the Azure CLI into the SimDem VirtualEnv

**Comment by SorraTheOrc** [comment] 2018-02-05 18:19
Closing as the refactoring work on SimDem will either significantly change the way this is done or outright solve it.

**Closed as completed by SorraTheOrc** 2018-02-05 18:19 UTC
Labels: bug, P-High
